[project]
name = "CLI-Toolkit"
version = "1.0.1"
description = "A compact and powerful command-line toolkit"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "rich>=15.0.0",
]

[tool.ruff.lint]
select = [
    "ARG",
    "B",
    "C4",
    "D",
    "E",
    "F",
    "G",
    "I",
    "LOG",
    "PTH",
    "SIM",
    "UP",
    "W",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.20.0",
    "pytest>=9.0.3",
    "ruff>=0.15.12",
]
